api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "stockly-volume-discount"
type = "function"
uid = "130ea9fa-9d1c-66d0-c746-1c291c4cb68d6b5138b4"
description = "t:description"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
