api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "stockly-opening-order"
type = "function"
uid = "592e9d84-d987-9979-26ce-fb0d1977b448faf66bd5"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
